### ISSUE TITLE
Circular reference Awaited in utils.d.ts

### ISSUE THREAD

**Issue by cyberworkz** [algolia/angular-instantsearch#835]
starting angular instantseach with ng server gives the following error messages

```
 export declare type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T;
                       ~~~~~~~
../../../node_modules/instantsearch.js/es/types/utils.d.ts:12:67 - error TS2315: Type 'Awaited' is not generic.
```

**Environment:**

 - algolia: 4.10.5
 - instantsearch 
 - Angular 11

**Comment by tkrugg** [comment]
Hi @cyberworkz, thanks for reaching out. This is more a typescript version issue.
What typescript version are you using? This should work in [any version >= 4.1.5](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAgg7gQwJbAgEwDwBUB8UC8UWUEAHqgHZoDOUACgE4D2AtktRADJIDWEGSCgDMIDKAFU8AfliIU6DJKgAuIgFgAUEA ). 
I'll close this for now, but feel free to reopen if you're still having issue after upgrading your typescript version.

**Comment by cyberworkz** [comment]
You are correct, thanks for the reply.

**Comment by danielkariti** [comment]
How to fix without upgrading TS? still encountering the issue and it's not possible to upgrade ts without breaking the whole system
